### ISSUE TITLE
web interface gpio configuration

### ISSUE THREAD

**Issue by dgcasana** [gmag11/EnigmaIOT#4]
I have been working since more than 15 days, and I also use tasmota.
I am thinking of changing my tasmota plugs to enigmaiot, and I think that it would not be very expensive to be able to configure the gpio from the web, even that it would support the tasmota templates (since it has a very large database).
this would make it much more accessible to non-advanced users in arduino

**Comment by gmag11** [comment]
In this moment, EnigmaIOT is in a quite early stage. Current priority is migrate gateway to a single esp32 board.
After that I can think about building a generic sensor platform  like Tasmota.
Indeed, this could be a separate project using EnigmaIOT as transport medium by using EnigmaIOTnode.h. That's why I designed it as a library.
